;;; Automatically generated by ‘recentf’ on Tue Jan 10 12:55:42 2023.

(setq recentf-list
      '(
        "/Users/pengyo/workspace/sicp/practice.scm"
        "/Users/pengyo/workspace/sicp/simple-integration.scm"
        "/Users/pengyo/workspace/java/jlox/com/interpreter/lox/Lox.java"
        "/Users/pengyo/workspace/java/head-first-java/Juxbox.java"
        "/Users/pengyo/workspace/python/lab/bacon/lab.py"
        "/Users/pengyo/workspace/python/lab/bacon/test.py"
        "/Users/pengyo/.emacs.d/init.el"
        "/Users/pengyo/.emacs.d/kbd.el"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test.py"
        "/Users/pengyo/workspace/python/lab/image_processing/lab.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/lab.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/cat_blurred5.png"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_grey.png"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_energy.pickle"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_1seam.png"
        "/Users/pengyo/workspace/python/lab/lab01/test.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_seam_carving_helpers.py"
        "/Users/pengyo/workspace/python/mylib.py"
        "/Users/pengyo/workspace/python/test/pset.py"
        "/Users/pengyo/workspace/test/hello.py"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
