;;; Automatically generated by ‘recentf’ on Sat Jan 28 18:19:25 2023.

(setq recentf-list
      '(
        "/Users/pengyo/.emacs.d/init.el"
        "/Users/pengyo/.emacs.d/kbd.el"
        "/Users/pengyo/workspace/java/head-first-java/Juxbox.java"
        "/Users/pengyo/.emacs.d/elpa/yasnippet-snippets-20220713.1234/snippets/cc-mode/for_n"
        "/Users/pengyo/.emacs.d/elpa/yasnippet-snippets-20220713.1234/snippets/c++-mode/fre"
        #("/Applications/Emacs.app/Contents/Resources/etc/NEWS" 0 51 (match-part "/Applications/Emacs.app/Contents/Resources/etc/NEWS"))
        "/Users/pengyo/workspace/python/lab/bacon/lab.py"
        "/Users/pengyo/workspace/java/jlox/com/interpreter/lox/Lox.java"
        "/Users/pengyo/workspace/sicp/practice.scm"
        "/Users/pengyo/workspace/sicp/calculus.scm"
        "/Users/pengyo/workspace/sicp/simple-integration.scm"
        "/Users/pengyo/workspace/python/lab/bacon/test.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test.py"
        "/Users/pengyo/workspace/python/lab/image_processing/lab.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/lab.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/cat_blurred5.png"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_grey.png"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_energy.pickle"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_1seam.png"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
