;;; Automatically generated by ‘recentf’ on Sun Jan  8 14:46:58 2023.

(setq recentf-list
      '(
        "/Users/pengyo/workspace/python/lab/bacon/lab.py"
        "/Users/pengyo/.emacs.d/init.el"
        "/Users/pengyo/.emacs.d/kbd.el"
        "/Users/pengyo/workspace/python/lab/bacon/test.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test.py"
        "/Users/pengyo/workspace/python/lab/image_processing/lab.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/lab.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/cat_blurred5.png"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_grey.png"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_energy.pickle"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_results/bluegill_1seam.png"
        "/Users/pengyo/workspace/python/lab/lab01/test.py"
        "/Users/pengyo/workspace/python/lab/image_processing_2/test_seam_carving_helpers.py"
        "/Users/pengyo/workspace/python/mylib.py"
        "/Users/pengyo/workspace/python/test/pset.py"
        "/Users/pengyo/workspace/test/hello.py"
        "/Users/pengyo/workspace/java/head-first-java/Juxbox.java"
        "/Users/pengyo/workspace/java/Main.java"
        "/Users/pengyo/workspace/cpp/hello/hello.cpp"
        "/Users/pengyo/.emacs.d/var/lsp-java/workspace/.cache/java.util.ArrayList.java"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
